const SOCKET_EVENTS = Object.freeze({
  MATCH_CREATED: "match_created",
  MATCH_CONFIRMED: "match_confirmed",
  MATCH_STARTED: "match_started",
  QUESTION_OPENED: "question_opened",
  QUESTION_CLOSED: "question_closed",
  QUESTION_CHANGED: "question_changed",
  INTERMISSION_STARTED: "intermission_started",
  INTERMISSION_ENDED: "intermission_ended",
  MATCH_CLOSED: "match_closed",
  MATCH_ENDED: "match_ended",
  MATCH_CANCELLED: "match_cancelled",
  TEAM_JOINED: "team_joined",
  TEAM_RECONNECTED: "team_reconnected",
  TEAM_DEVICE_SWITCH_REQUIRED: "team_device_switch_required",
  TEAM_DEVICE_SWITCHED: "team_device_switched",
  TEAM_LEFT: "team_left",
  TEAM_REMOVED: "team_removed",
  TEAM_RESTORED: "team_restored",
  ANSWER_SUBMITTED: "answer_submitted",
  ANSWER_REOPENED: "answer_reopened",
  TEAM_ANSWER_STATUS_UPDATED: "team_answer_status_updated",
  ANSWER_REVIEWED: "answer_reviewed",
  SCORE_UPDATED: "score_updated",
  SCORE_LOG_CREATED: "score_log_created",
  LEADERBOARD_UPDATED: "leaderboard_updated",
  JOIN_MATCH_ROOM: "join_match_room",
  JOIN_TEAM_ROOM: "join_team_room",
  JOIN_PRESENTATION_ROOM: "join_presentation_room",
  LEAVE_ROOM: "leave_room",
  REQUEST_LEADERBOARD: "request_leaderboard",
  REQUEST_MATCH_STATE: "request_match_state",
  MATCH_STATE_UPDATED: "match_state_updated",
  QUESTION_STATE_UPDATED: "question_state_updated",
  TEAM_SCORE_UPDATED: "team_score_updated",
  SOCKET_ERROR: "socket_error",
});

module.exports = SOCKET_EVENTS;
